name: pax-config
version: '1.0'
description: PAX package manager configuration file
license: GPL-3.0-or-later
homepage: ''
source_url: null
build:
  build_system: Make
  build_commands:
  - rm -rf src-package || true
  - mkdir -p etc/pax
  - echo 'sourcetype=repo url="https://repo.almalinux.org/almalinux/10.0/AppStream/x86_64/os/" provider="rpm"' > etc/pax/sources.conf
  - echo 'sourcetype=repo url="https://repo.almalinux.org/almalinux/10.0/devel/x86_64/os/" provider="rpm"' >> etc/pax/sources.conf
dependencies:
  build_dependencies: []
  host_dependencies: []
  runtime_dependencies:
  - glibc
  - coreutils
bootstrap:
  enabled: false
changelog:
- version: '1.0'
  date: '2026-01-03'
  author: Oreon Project Team
  email: packaging@oreonproject.org
  changes:
  - Initial package for Oreon 11
