name: fontconfig
version: 2.15.0
description: fontconfig - font configuration library
license: MIT
homepage: https://www.freedesktop.org/wiki/Software/fontconfig/
source_url: https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.15.0.tar.xz
build:
  build_system: Autotools
  build_commands:
  - ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
dependencies:
  build_dependencies: []
  host_dependencies: []
  runtime_dependencies:
  - glibc
bootstrap:
  enabled: false
changelog:
- version: 2.15.0
  date: '2026-01-03'
  author: Oreon Project Team
  email: packaging@oreonproject.org
  changes:
  - Initial package for Oreon 11
