name: xkeyboard-config
version: '2.43'
description: X Keyboard Configuration Database
license: MIT
homepage: https://www.freedesktop.org/wiki/Software/XKeyboardConfig/
source_url: https://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.43.tar.xz
build:
  build_system: Make
  build_commands:
  - meson setup build --prefix=/usr
  - ninja -C build
dependencies:
  build_dependencies:
  - gcc
  - make
  - meson
  - ninja
  host_dependencies: []
  runtime_dependencies:
  - glibc
bootstrap:
  enabled: false
changelog:
- version: '2.43'
  date: '2026-01-03'
  author: Oreon Project Team
  email: packaging@oreonproject.org
  changes:
  - Initial package for Oreon 11
